spring:
  application:
    name: catalog-service

  main:
    lazy-initialization: true        # ⚡ Carga los beans solo cuando se usan
    banner-mode: off                 # Evita carga del banner ASCII

  datasource:
    url: jdbc:postgresql://localhost:5432/Cetpro
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 15          # ⚙️ Pool ajustado
      minimum-idle: 3
      idle-timeout: 300000
      max-lifetime: 1800000
      initializationFailTimeout: 0   # ⚡ No espera si la BD tarda

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  cloud:
    config:
      request-read-timeout: 2000     # ⚡ Timeout corto para Config Server
      retry:
        max-attempts: 2
        initial-interval: 1000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30
    initial-instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-seconds: 15
    lease-expiration-duration-seconds: 40

server:
  port: 8082

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  info:
    env:
      enabled: true

logging:
  level:
    root: warn                       # ⚡ Menos carga en consola
    org.springframework: info

info:
  app:
    name: Servicio de Catálogo (catalog-service)
    description: Expone los endpoints REST principales del sistema (alumnos, docentes, matrículas, módulos, etc.).
    version: 1.0.0
    author: Ricardo Terrazas
    environment: desarrollo