spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Finance
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      catalogService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30
    initial-instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-seconds: 15
    lease-expiration-duration-seconds: 40

server:
  port: 8084

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  info:
    env:
      enabled: true

logging:
  level:
    root: warn                       # ⚡ Menos carga en consola
    org.springframework: info

info:
  app:
    name: Servicio de Finanzas (finance-service)
    description: Servicio encargado de la gestión financiera, donde se manejan transacciones y reportes, ademas se conecta con el servicio de catalogo para obtener informacion de productos.
    version: 1.0.0
    author: Ricardo Terrazas
    environment: desarrollo